import type { Route } from "./+types/home"; //TypeScript types generated by React Router for this route. helps with type safety in loader, action, and meta.
import { SignUp } from "~/ui/signUp";

export function meta({}: Route.MetaArgs) {
	//metadata for SEO
	return [
		{ title: "Chatbot App Home" },
		{ name: "description", content: "A chatbot app with React Router" },
	];
}

export default function Home() {
	const account = false;

	
    if (!account) {
      return (
      	<div className="min-h-screen flex justify-center bg-gray-100">
			<h1 className="text-4xl font-bold font-Roboto drop-shadow-blue-300 drop-shadow-md text-center text-blue-700">
				Home
			</h1>
		</div>
      );
    }
    else {
      return <SignUp/>
    }
}
