import { authClient } from "~/lib/auth-client";
import type { Route } from "./+types/home"; //TypeScript types generated by React Router for this route. helps with type safety in loader, action, and meta.
import { Link } from "react-router";
import { account } from "../db/auth-schema";
import Spinner from "ui/Spinner";

export function meta({}: Route.MetaArgs) {
	//metadata for SEO
	return [
		{ title: "Chatbot App Home" },
		{ name: "description", content: "A chatbot app with React Router" },
	];
}

export default function Home() {
	//RPGpt
	const { data, isPending, error } = authClient.useSession();

	if (isPending) {
		<Spinner size={200}/>
	}

	if (error) {
		return <div>Error loading session: {error.message}</div>;
	}

	return (
		<div className="min-h-screen bg-gray-50">
			<div className="w-full flex flex-col items-center justify-start">
				<h1 className="text-4xl font-bold font-Roboto drop-shadow-md text-center text-gray-900">
					Welcome to Chatbot
				</h1>
				<div className="flex items-center justify-center">
					<Link
						to="/signUp"
						className="m-2 px-4 py-2 bg-indigo-600 text-white rounded-lg shadow hover:bg-indigo-700"
					>
						Create an account
					</Link>
					<Link
						to="/signUp"
						className="m-2 px-4 py-2 bg-indigo-600 text-white rounded-lg shadow hover:bg-indigo-700"
					>
						Sign In
					</Link>
				</div>
			</div>
		</div>
	);
}
