import type { Route } from "./+types/home"; //TypeScript types generated by React Router for this route. helps with type safety in loader, action, and meta.

export function meta({}: Route.MetaArgs) { //metadata for SEO
  return [
    { title: "Chatbot App Home" },
    { name: "description", content: "A chatbot app with React Router" },
  ];
}

export default function Home() {
  return <div className="min-h-screen flex justify-center bg-gray-100">
    <h1 className="text-4xl font-bold text-center text-blue-700">Home</h1>
  </div>;
}
